services:
  development:
    image: r2_humble
    
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp  # or rmw_cyclonedds_cpp
      - ROS_DOMAIN_ID=0  # Use the same domain ID
    
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /home/keitheorem/torch:/home/keitheorem/torch
    
    user: "keitheorem"
    
    network_mode: host
    stdin_open: true   # Equivalent to -i (interactive mode)
    tty: true          # Equivalent to -t (TTY)

    deploy:
      resources:
        reservations: 
          devices:
            - driver: nvidia
              capabilities: [gpu] 

    working_dir: /home/keitheorem/ros2_ws  # Set the working directory

  publisher_node:
    image: r2_humble
    
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp  # or rmw_cyclonedds_cpp
      - ROS_DOMAIN_ID=0  # Use the same domain ID
    
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /home/keitheorem/torch:/home/keitheorem/torch
    
    user: "keitheorem"
    
    network_mode: host
    stdin_open: true   # Equivalent to -i (interactive mode)
    tty: true          # Equivalent to -t (TTY)

    deploy:
      resources:
        reservations: 
          devices:
            - driver: nvidia
              capabilities: [gpu] 

    working_dir: /home/keitheorem/ros2_ws  # Set the working directory
    command: 
    - ros2 run sub_pub publisher_node 

  subscriber_node:
    image: r2_humble
    
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp  # or rmw_cyclonedds_cpp
      - ROS_DOMAIN_ID=0  # Use the same domain ID
    
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /home/keitheorem/torch:/home/keitheorem/torch
    
    user: "keitheorem"
    
    network_mode: host
    stdin_open: true   # Equivalent to -i (interactive mode)
    tty: true          # Equivalent to -t (TTY)
    
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu] 

    working_dir: /home/keitheorem/ros2_ws  # Set the working directory
    command: ros2 run sub_pub subscriber_node  
